name: Build & Deploy

on:
  push:
    branches:
      - master  # Adjust branch name as per your main branch

jobs:
  build-deploy:
    name: Build & Deploy hfo Server
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Setup JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      # Step 3: Build the application
      - name: Build the application
        run: |
          ./gradlew clean
          ./gradlew --no-daemon build

      # Step 4: Get current date and time in IST
      - name: Get current date and time in IST
        id: vars
        run: |
          IST_DATE=$(TZ='Asia/Kolkata' date +'%Y%m%d%H%M')
          echo "TAG=$IST_DATE" >> $GITHUB_ENV

      # Step 5: Login to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # Step 6: Build and Push Docker Image To Docker Hub
      - name: Build and Push Docker Image To Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          dockerfile: Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/hfo:${{ env.TAG }}

      # Step 8: Deploy to Server
      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/hfo:${{ env.TAG }}
            docker stop hfo || true && docker rm hfo || true
            docker run -d --name hfo -p 8449:8080 ${{ secrets.DOCKER_HUB_USERNAME }}/hfo:${{ env.TAG }}